[theme]
# Streamlit theme configuration for better user experience
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
# Server configuration for cloud deployment
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
# Browser configuration
gatherUsageStats = false

[runner]
# Performance optimizations for cloud deployment
magicEnabled = true

[logger]
# Logging configuration
level = "info"